server:
  name: "TiktokAPIServer"
  host: 0.0.0.0
  port: 8089
  limit:
    capacity: 200
    rate: 20
    tokenInit: 128  # 初始令牌个数

JWT:
  signingKey: "signingKey"

Etcd:
  enable: true
  host: 0.0.0.0
  port: 2379

Hertz:
  useNetPoll: false
  tls:
    enable: false
    keyFile: ""
    certFile: ""
    ALPN: true
  http2:
    enable: false
    keyFile: ""
    certFile: ""
    ALPN: true