endpoint: 0.0.0.0:9000
accessKeyId: minio
secretAccessKey: 12345678
useSSL: false
avatarBucketName: avatars
backgroundImageBucketName: bgimages
videoBucketName: videos
coverBucketName: video-covers
expire: 3600
