endpoint: 192.168.197.130:9000
# endpoint: 154.8.205.192:9000
accessKeyId: minio
secretAccessKey: 12345678
useSSL: false
avatarBucketName: avatars
backgroundImageBucketName: bgimages
videoBucketName: videos
coverBucketName: video-covers
expire: 3600
