message:
  name: "message"
  host: 0.0.0.0
  port: 8083
api-gateway:
  host: 0.0.0.0
  port: 8080
user:
  name: "TiktokUserServer"
  host: 0.0.0.0
  port: 8084

favorite:
  name: "favorite"
  host: 0.0.0.0
  port: 8085
relation:
  name: "relation"
  host: 0.0.0.0
  port: 8086
feed:
  name: "feed"
  host: 0.0.0.0
  port: 8087
publish:
  name: "publish"
  host: 0.0.0.0
  port: 8088
  videoMaxSize: 50
comment:
  name: "comment"
  host: 0.0.0.0
  port: 8089
